# ALPINE LINUX ARM WOOO!
FROM armhf/alpine as build

RUN apk update && apk add fbida-fbi && apk add ttf-dejavu && \
    wget http://www.dailymobile.net/wp-content/uploads/2009/04/nokia-e66-wallpapers-320x240-landscape-06.jpg -O image.jpeg
